apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  selector:
    matchLabels:
      app: web
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      labels:
        io.kompose.network/learning-app-ecommerce-kodekloud-net: "true"
        io.kompose.service: web
        app: web
    spec:
      serviceAccountName: web
      containers:
        - image: robra24/ecommerce:1.0.0
          name: web
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP

          resources:
            limits:
              memory: "512Mi"  
              cpu: "500m"      
            requests:
              memory: "512Mi"  
              cpu: "500m"      
      restartPolicy: Always
